language: node_js

node_js:
  - "node"
  - "7.6"
  - "8"
  - "9"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm install -g codecov

script:
  - npm run lint
  - npm test

after_success:
  - codecov
