language: node_js

node_js:
  - "8.9"
  - "8"
  - "9.0"
  - "9"
  - "10.0"
  - "10"
  - "11.0"
  - "11"
  - "12.0"
  - "12"
  - "13.0"
  - "13"
  - "node"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm install -g codecov

script:
  - npm test

after_success:
  - codecov

jobs:
  include:
    - name: Lint
      node_js: "node"
      before_install: skip
      script:
        - npm run lint
      after_success: skip
    - stage: npm release
      if: tag IS present
      node_js: "node"
      cache: {}
      before_install: skip
      install: skip
      script: skip
      after_success:
        - '(cd manual && make)'
      deploy:
        provider: npm
        edge: true
        email: thinca+npm@gmail.com
        api_key:
          secure: "LwQifeHiLX13q0rStuX2JCQgvGLFqo25Dqrco2b0RkbEApyu/wAmBki5zzG8Kk9UdSzyAUXCx1mnIEWvOVr1PObnvvkKx1TXK/Awi8mfZs08bBun6WfJOmk/lbKOv1sQqU3/Z+MQ6NX3GrbE4MoE7dscEdbl6Fc7C1mRRGH0ZhIudn18EF4g+pwaPCfQrtWoQgGpmZC9fnEwIxxqvRpPDmAKKfhAtwLl3F8Tqp1uZwQ0qTDxVKKh0deTLmmMEcXKbAOXkDZxS0pPR3Yk02FiUX5ty3RLdd8lXAYY6F6keZX3vOSWtQl6TOT2FmaZ7in3p4Q9JUOySeNXYHgyIpM/nLwbfv8dKp2W5EPObUpUuN9vuh312VE7x+KtY90FiM+yKl5ujKMK3Bq2ikefiYYsYipNE5inu5vuiJSrc12NIuzjvduWL3VxtgNHRaaEOcpGNQDFLtX5CdIP2f3AoGeiFcSWDz4kFhdn98T3PEDTt4EjREqQfLLEIdSxLv389hlzOuC8O9IF5HTaIkOhtnTIjnGFARXLaycoXepFx6SgygWvrBXVrqwZyxBoCOytdIdMiUS/imByIYfJksoDS12NMSeeG0afEhUQfruehNLEo2ekKiQ8bti2BXpSuQVKv8I9LVn5verzANFb27iWkU3U0cvt6o76bjAvgAB5EW4YlIk="
        skip_cleanup: true
        on:
          tags: true
