name: 'Publish'
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
    branches:
      - 'v*.*.*'

jobs:
  publish:
    name: 'Publish'
    if: "github.event.workflow_run.conclusion == 'success'"
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Setup Node.js 12 (LTS)'
        uses: 'actions/setup-node@v2-beta'
        with:
          node-version: '12'
      - run: npm install -g npm@v7
      - uses: 'bahmutov/npm-install@v1'
      - name: 'Prepare for publishing a new npm package'
        run: |
          npm run --silent man
      - name: 'Publish a new npm package'
        uses: 'JS-DevTools/npm-publish@v1'
        with:
          token: ${{ secrets.NPM_TOKEN }}
